import type { Metadata } from "next";
import { NavbarDemo } from "@/components/global/header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SocialLinks from "@/components/global/socials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FAF7F0]`}
      >
        <NavbarDemo />
        {children}
        {/* <SocialLinks /> */}
      </body>
    </html>
  );
}
